<template><div><h1 id="utilizare-avansata-a-props-urilor" tabindex="-1"><a class="header-anchor" href="#utilizare-avansata-a-props-urilor"><span>Utilizare avansată a props-urilor</span></a></h1>
<p>În lecția anterioară, am discutat despre componente în React și abordarea bazată pe componente pentru crearea interfețelor utilizatorilor. În această lecție, vom explora props-urile (props) și caracteristicile lor.</p>
<p>Props-urile sunt, în esență, argumentele unei funcții care permit influențarea randării elementelor în interiorul componentelor și logica funcționării lor. Ca și un argument, un prop poate fi orice: o funcție, un obiect, un array, un șir de caractere, un număr.</p>
<p>Știți deja că React, când lucrează cu componente, combină atributele JSX într-un singur obiect - <mark>props</mark>.</p>
<p>Într-o componentă de clasă, accesul la acest obiect se poate obține prin <mark>this.props</mark>, iar într-o componentă funcțională, <mark>props</mark> este disponibil ca primul argument al funcției:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">Heading</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token operator">&lt;</span>h1<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>text<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>h1<span class="token operator">></span>
<span class="token punctuation">}</span>

<span class="token keyword">const</span> root <span class="token operator">=</span> ReactDOM<span class="token punctuation">.</span><span class="token function">createRoot</span><span class="token punctuation">(</span>document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'#root'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
root<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span><span class="token operator">&lt;</span>Heading text<span class="token operator">=</span><span class="token string">"Titlul unui articol interesant"</span> <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Ca nume al argumentului, este obișnuit să se folosească <mark>props</mark>.
Recomandăm să numiți argumentul exact așa: acest lucru va simplifica percepția codului dvs. de către alți dezvoltatori, deoarece mulți dintre ei urmează și ei acest principiu.</p>
<p>În lecția despre <a href="/base/composition">compoziție și extragerea componentelor</a>, ați văzut deja că pot exista mai multe props-uri și structura lor permite încorporarea:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token function-variable function">Product</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
    <span class="token operator">&lt;</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>productData<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span> <span class="token punctuation">{</span><span class="token comment">/* Costum de scafandru */</span><span class="token punctuation">}</span>
        <span class="token operator">&lt;</span>span<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>productData<span class="token punctuation">.</span>price<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>span<span class="token operator">></span> <span class="token punctuation">{</span><span class="token comment">/* 14299 */</span><span class="token punctuation">}</span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token function-variable function">ShoppingCart</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
    <span class="token operator">&lt;</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>h1<span class="token operator">></span>Coș de cumpărături<span class="token operator">&lt;</span><span class="token operator">/</span>h1<span class="token operator">></span>
        <span class="token operator">&lt;</span>Product productData<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Costum de scafandru"</span><span class="token punctuation">,</span> <span class="token literal-property property">price</span><span class="token operator">:</span> <span class="token number">14299</span> <span class="token punctuation">}</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span><span class="token operator">></span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>În acest exemplu, componenta <mark>ShoppingCart</mark> &quot;randează&quot; o altă componentă - <mark>Product</mark>.
Ca argumente (props-uri), i se transmite un obiect cu două valori: <mark>name</mark> și <mark>price</mark>.</p>
<p>Pentru a face codul mai lizibil, ar trebui să simplificați structura props-urilor transmise componentei și să utilizați ca argumente primitive. Acest lucru nu va afecta performanța, deoarece React este foarte rapid, dar lucrul cu primitivele este mai simplu.</p>
<p>Priviți exemplul în care <mark>props</mark> este un obiect complex:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token comment">// Componentă</span>
<span class="token keyword">const</span> <span class="token function-variable function">Product</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
    <span class="token operator">&lt;</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>productData<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span> <span class="token punctuation">{</span><span class="token comment">/* Costum de scafandru */</span><span class="token punctuation">}</span>
        <span class="token operator">&lt;</span>span<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>productData<span class="token punctuation">.</span>price<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>span<span class="token operator">></span> <span class="token punctuation">{</span><span class="token comment">/* 14299 */</span><span class="token punctuation">}</span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Utilizarea componentei</span>
<span class="token operator">&lt;</span>Product productData<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">{</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"Costum de scafandru"</span><span class="token punctuation">,</span> <span class="token literal-property property">price</span><span class="token operator">:</span> <span class="token number">14299</span> <span class="token punctuation">}</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Codul care utilizează această componentă pare complicat, iar implementarea internă necesită mai multă atenție din partea dezvoltatorului. Să simplificăm această componentă:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token comment">// Componentă</span>
<span class="token keyword">const</span> <span class="token function-variable function">Product</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
    <span class="token operator">&lt;</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span> <span class="token punctuation">{</span><span class="token comment">/* Costum de scafandru */</span><span class="token punctuation">}</span>
        <span class="token operator">&lt;</span>span<span class="token operator">></span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>price<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>span<span class="token operator">></span> <span class="token punctuation">{</span><span class="token comment">/* 14299 */</span><span class="token punctuation">}</span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Utilizarea componentei</span>
<span class="token operator">&lt;</span>Product name<span class="token operator">=</span><span class="token string">"Costum de scafandru"</span> price<span class="token operator">=</span><span class="token punctuation">{</span><span class="token number">14299</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Din exemplu se vede că implementarea s-a simplificat, iar utilizarea componentei a devenit mai declarativă.</p>
<h2 id="props-urile-pot-fi-doar-citite" tabindex="-1"><a class="header-anchor" href="#props-urile-pot-fi-doar-citite"><span>Props-urile pot fi doar citite</span></a></h2>
<p>Componentele React trebuie să se comporte ca funcții &quot;pure&quot; în raport cu props-urile lor, indiferent dacă sunt funcționale sau de clasă. Acest lucru înseamnă că componentele nu ar trebui să scrie ceva în props-urile lor. Să analizăm acest lucru pe exemplul funcțiilor &quot;pure&quot; și &quot;impure&quot;.</p>
<p>Funcția <mark>formatPrice</mark> este &quot;pură&quot;, deoarece</p>
<p>nu modifică datele de intrare și returnează în mod previzibil același rezultat pentru aceleași argumente:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">formatPrice</span><span class="token punctuation">(</span><span class="token parameter">price</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> price <span class="token operator">+</span> <span class="token string">'MDL'</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>În schimb, funcția <mark>notificationSettings</mark> este &quot;impură&quot;, deoarece scrie date în propriul său argument - obiectul <mark>user</mark>:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">notificationSettings</span><span class="token punctuation">(</span><span class="token parameter">user<span class="token punctuation">,</span> notificationValue</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  user<span class="token punctuation">.</span>notifications <span class="token operator">=</span> notificationValue<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Pentru ca dezvoltarea în React să rămână previzibilă și convenabilă, props-urile trebuie să fie accesibile doar pentru citire.</p>
<p>În lecțiile următoare, vom discuta cum să influențăm props-urile unei componente din interiorul acestei componente.</p>
<h2 id="expresii-javascript-ca-props-uri" tabindex="-1"><a class="header-anchor" href="#expresii-javascript-ca-props-uri"><span>Expresii JavaScript ca props-uri</span></a></h2>
<p>Ca props-uri, puteți transmite orice expresii JavaScript.
Pentru acest lucru, trebuie să le înconjurați cu <mark>{}</mark>. De exemplu, în acest JSX:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>MusicGenreItem genre<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">'rock'</span> <span class="token operator">+</span> <span class="token string">'&amp;'</span> <span class="token operator">+</span> <span class="token string">'roll'</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>În componenta <mark>MusicGenreItem</mark>, valoarea <mark>props.genre</mark> va fi egală cu <mark>rock&amp;roll</mark>, deoarece expresia <mark>'rock' + '&amp;' + 'roll'</mark> va fi evaluată. Același lucru este valabil și pentru funcții:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">sayHi</span><span class="token punctuation">(</span><span class="token parameter">name</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Salut, </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>name<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">!</span><span class="token template-punctuation string">`</span></span>
<span class="token punctuation">}</span>

<span class="token operator">&lt;</span>WelcomeComponent textToRender<span class="token operator">=</span><span class="token punctuation">{</span><span class="token function">sayHi</span><span class="token punctuation">(</span><span class="token string">'Nicolai'</span><span class="token punctuation">)</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>În acest exemplu, în prop-ul <mark>textToRender</mark> va ajunge rezultatul executării funcției <mark>sayHi('Nicolai')</mark>, adică șirul <mark>&quot;Salut, Nicolai!&quot;</mark>.</p>
<p>Operatorii <mark>if</mark>, <mark>switch</mark> și ciclul <mark>for</mark> nu sunt expresii în JavaScript. Din acest motiv, nu pot fi aplicate direct în JSX.
Pentru a le utiliza, trebuie mai întâi să obțineți rezultatul lucrării acestor operatori, iar apoi acest rezultat să-l plasați în codul JSX:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">TrafficLightComponent</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> action<span class="token punctuation">;</span>
  <span class="token keyword">switch</span> <span class="token punctuation">(</span>props<span class="token punctuation">.</span>color<span class="token punctuation">)</span> <span class="token punctuation">{</span> 
        <span class="token keyword">case</span> <span class="token string">"red"</span><span class="token operator">:</span>   
            action <span class="token operator">=</span> <span class="token operator">&lt;</span>b<span class="token operator">></span>Stai<span class="token operator">&lt;</span><span class="token operator">/</span>b<span class="token operator">></span>
        <span class="token keyword">case</span> <span class="token string">"yellow"</span><span class="token operator">:</span>
            action <span class="token operator">=</span> <span class="token operator">&lt;</span>i<span class="token operator">></span>Finalizează manevra<span class="token operator">&lt;</span><span class="token operator">/</span>i<span class="token operator">></span>
        <span class="token keyword">case</span> <span class="token string">"green"</span><span class="token operator">:</span>
            action <span class="token operator">=</span> <span class="token operator">&lt;</span>strong<span class="token operator">></span>Trece<span class="token operator">&lt;</span><span class="token operator">/</span>strong<span class="token operator">></span><span class="token punctuation">;</span>  
        <span class="token keyword">default</span><span class="token operator">:</span>
            action <span class="token operator">=</span> <span class="token operator">&lt;</span>span<span class="token operator">></span>Fii atent<span class="token punctuation">,</span> semaforul nu funcționează<span class="token operator">&lt;</span><span class="token operator">/</span>span<span class="token operator">></span>  
    <span class="token punctuation">}</span>  
    <span class="token keyword">return</span> <span class="token operator">&lt;</span>div<span class="token operator">></span>Semaforul recomandă<span class="token operator">:</span> <span class="token punctuation">{</span>action<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="literali-de-siruri-de-caractere-ca-props-uri" tabindex="-1"><a class="header-anchor" href="#literali-de-siruri-de-caractere-ca-props-uri"><span>Literali de șiruri de caractere ca props-uri</span></a></h2>
<p>Literali de șiruri de caractere pot fi, de asemenea, utilizați ca props-uri.</p>
<p>De exemplu, aceste componente sunt echivalente:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>WelcomeComponent name<span class="token operator">=</span><span class="token string">"Carol Danvers"</span> <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&lt;</span>WelcomeComponent name<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">'Carol Danvers'</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&lt;</span>WelcomeComponent name<span class="token operator">=</span><span class="token punctuation">{</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Carol Danvers</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&lt;</span>WelcomeComponent name<span class="token operator">=</span><span class="token string">'Carol Danvers'</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Dacă transmiteți un literal de șir de caractere într-o componentă, toate simbolurile sale posibile vor fi transformate în entități HTML corespunzătoare. Aceste două componente sunt echivalente:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>FavoritePet pet<span class="token operator">=</span><span class="token string">"&amp;#128008;"</span> <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&lt;</span>FavoritePet pet<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">'🐈'</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="valorile-implicite-ale-props-urilor-sunt-true" tabindex="-1"><a class="header-anchor" href="#valorile-implicite-ale-props-urilor-sunt-true"><span>Valorile implicite ale props-urilor sunt true</span></a></h2>
<p>Dacă se transmite o valoare într-un prop, implicit va fi <mark>true</mark>.
Aceste două expresii JSX sunt echivalente:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>TextInput disabled <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&lt;</span>TextInput disabled<span class="token operator">=</span><span class="token punctuation">{</span><span class="token boolean">true</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Această caracteristică a props-urilor în componentele React există pentru a se conforma comportamentului HTML obișnuit. Este mai bine să nu vă bazați pe această caracteristică și să specificați valorile props-urilor în mod explicit, deoarece altfel această înregistrare poate fi interpretată de React ca o notație scurtă a proprietăților obiectului:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> title <span class="token operator">=</span> <span class="token string">"Autostop prin Moldova"</span>

<span class="token punctuation">{</span> title <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Această înregistrare este echivalentă cu obiectul <mark>{ title: &quot;Autostop prin Moldova&quot; }</mark>, dar cu siguranță nu cu obiectul <mark>{ title: true }</mark>.</p>
<h2 id="atribute-de-extindere" tabindex="-1"><a class="header-anchor" href="#atribute-de-extindere"><span>Atribute de extindere</span></a></h2>
<p>Structura încorporată a props-urilor este o situație frecventă, mai ales când lucrați cu</p>
<p>un server care returnează un JSON multi-nivel. Pentru a face codul mai compact și mai lizibil, puteți utiliza operatorul de extindere. În acest exemplu, ambele componente sunt identice:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">CutomerPage</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span>
        <span class="token operator">&lt;</span>ProfileInfo 
            firstName<span class="token operator">=</span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>profileData<span class="token punctuation">.</span>firstName<span class="token punctuation">}</span>
            lastName<span class="token operator">=</span><span class="token punctuation">{</span>props<span class="token punctuation">.</span>profileData<span class="token punctuation">.</span>lastName<span class="token punctuation">}</span>
        <span class="token operator">/</span><span class="token operator">></span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">function</span> <span class="token function">CutomerPage</span><span class="token punctuation">(</span><span class="token parameter">props</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token operator">&lt;</span>ProfileInfo <span class="token punctuation">{</span><span class="token operator">...</span>props<span class="token punctuation">.</span>profileData<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Operatorul de extindere ajută la filtrarea props-urilor necesare și la transmiterea în componenta țintă doar a datelor necesare:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token function-variable function">Input</span> <span class="token operator">=</span> <span class="token parameter">props</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token punctuation">{</span> size<span class="token punctuation">,</span> userId<span class="token punctuation">,</span> <span class="token operator">...</span>otherProps <span class="token punctuation">}</span> <span class="token operator">=</span> props<span class="token punctuation">;</span>  
    <span class="token keyword">const</span> className <span class="token operator">=</span> size <span class="token operator">===</span> <span class="token string">"default"</span> <span class="token operator">?</span> <span class="token string">"DefaultInput"</span> <span class="token operator">:</span> <span class="token string">"SmallInput"</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> <span class="token operator">&lt;</span>input className<span class="token operator">=</span><span class="token punctuation">{</span>className<span class="token punctuation">}</span> <span class="token punctuation">{</span><span class="token operator">...</span>otherProps<span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token function-variable function">LandingPage</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">(</span>
    <span class="token operator">&lt;</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>b<span class="token operator">></span>Introduceți codul promoțional<span class="token operator">:</span><span class="token operator">&lt;</span><span class="token operator">/</span>b<span class="token operator">></span>     
            <span class="token operator">&lt;</span>Input size<span class="token operator">=</span><span class="token string">"default"</span> type<span class="token operator">=</span><span class="token string">"text"</span> disabled<span class="token operator">=</span><span class="token punctuation">{</span><span class="token boolean">false</span><span class="token punctuation">}</span> userId<span class="token operator">=</span><span class="token punctuation">{</span><span class="token number">1112983</span><span class="token punctuation">}</span> <span class="token operator">/</span><span class="token operator">></span>    
        <span class="token operator">&lt;</span><span class="token operator">/</span><span class="token operator">></span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>În acest exemplu, în componenta <mark>Input</mark> sunt transmise următoarele props-uri:</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token punctuation">{</span>
    <span class="token literal-property property">size</span><span class="token operator">:</span> <span class="token string">"default"</span><span class="token punctuation">,</span>
    <span class="token literal-property property">type</span><span class="token operator">:</span><span class="token string">"text"</span><span class="token punctuation">,</span> 
    <span class="token literal-property property">disabled</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span> 
    <span class="token literal-property property">userId</span><span class="token operator">:</span> <span class="token number">1112983</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>În timp ce props-urile <mark>size</mark> și <mark>userId</mark> sunt folosite în siguranță și nu sunt transmise în elementul DOM <mark>&lt;input/&gt;</mark>. Prop-ul <mark>size</mark> este folosit intern pentru a calcula clasa, iar <mark>userId</mark> nu este folosit deloc.
Prin urmare, în obiectul <mark>otherProps</mark> rămân doar props-urile necesare elementului DOM - <mark>type</mark> și <mark>disabled</mark>.</p>
<p>Atributele de extindere pot fi utile și reduc codul, dar există riscul de a transmite props-uri suplimentare în componente sau atribute HTML nevalide în DOM. Utilizați acest instrument cu prudență.</p>
<h2 id="props-uri-pe-scurt-despre-principal" tabindex="-1"><a class="header-anchor" href="#props-uri-pe-scurt-despre-principal"><span>Props-uri: pe scurt despre principal</span></a></h2>
<p>În această lecție, ne-am aprofundat în posibilitățile props-urilor componentelor React.</p>
<p>Reamintim cele mai importante aspecte:</p>
<ul>
<li>Props-urile pot fi doar citite.</li>
<li>Props-urile pot fi orice expresii JavaScript.</li>
<li>Implicit, valorile props-urilor sunt setate la true.</li>
<li>Props-urile pot fi transmise în bloc cu ajutorul operatorului de extindere.</li>
<li>Un dezvoltator React aplică aceste abilități în mod regulat, iar abilitatea de a &quot;prepara&quot; corect props-urile influențează semnificativ calitatea și fiabilitatea codului. În lecția următoare, vom discuta despre starea internă și vom analiza cum să o utilizăm împreună cu props-urile.</li>
</ul>
</div></template>


